=== Darkxell/PMDMMO/PMDMMO-common/resources/data/xsd/quiz.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="pmdmmo" targetNamespace="pmdmmo"
    elementFormDefault="qualified">
    <xs:include schemaLocation="base.xsd"/>

    <xs:element name="quiz">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="questions">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="questiongroup" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="question" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="posInt" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="starters">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="starter" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="partners">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="partner" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="question">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="answer" maxOccurs="unbounded" minOccurs="2"/>
            </xs:sequence>
            <xs:attribute name="id" type="posInt" use="required"/>
            <xs:attribute name="yesno" type="xs:boolean" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="answer">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="reward" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:attribute name="nature" type="nature" use="required"/>
                        <xs:attribute name="value" type="xs:positiveInteger" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="posInt" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="starter">
        <xs:complexType>
            <xs:attribute name="nature" type="nature" use="required"/>
            <xs:attribute name="gender" use="optional">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="Boy"/>
                        <xs:enumeration value="Girl"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="pokemon" type="xs:positiveInteger" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="partner">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="invalidates" type="xs:positiveInteger" minOccurs="0"
                    maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="pokemon" type="xs:positiveInteger" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="nature">
        <xs:restriction base="xs:token">
            <xs:enumeration value="Hardy"/>
            <xs:enumeration value="Docile"/>
            <xs:enumeration value="Brave"/>
            <xs:enumeration value="Jolly"/>
            <xs:enumeration value="Impish"/>
            <xs:enumeration value="Naive"/>
            <xs:enumeration value="Timid"/>
            <xs:enumeration value="Hasty"/>
            <xs:enumeration value="Sassy"/>
            <xs:enumeration value="Calm"/>
            <xs:enumeration value="Relaxed"/>
            <xs:enumeration value="Lonely"/>
            <xs:enumeration value="Quirky"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== Darkxell/PMDMMO/PMDMMO-common/resources/data/quiz.xml
<?xml version="1.0" encoding="UTF-8"?>
<quiz xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="pmdmmo"
    xsi:schemaLocation="pmdmmo xsd/quiz.xsd">
    <questions>
        <questiongroup id="0">
            <question id="0">
                <answer id="0">
                    <reward nature="Hardy" value="2"/>
                </answer>
                <answer id="1">
                    <reward nature="Relaxed" value="2"/>
                </answer>
                <answer id="2">
                    <reward nature="Impish" value="2"/>
                </answer>
            </question>
            <question id="1">
                <answer id="0">
                    <reward nature="Hardy" value="2"/>
                    <reward nature="Docile" value="1"/>
                </answer>
                <answer id="1">
                    <reward nature="Quirky" value="2"/>
                </answer>
            </question>
            <question id="2">
                <answer id="0">
                    <reward nature="Hardy" value="2"/>
                    <reward nature="Brave" value="2"/>
                </answer>
                <answer id="1">
                    <reward nature="Sassy" value="2"/>
                    <reward nature="Quirky" value="2"/>
                </answer>
            </question>
            <question id="3">
                <answer id="0">
                    <reward nature="Hardy" value="2"/>
                </answer>
                <answer id="1">
                    <reward nature="Calm" value="2"/>
                </answer>
                <answer id="2">
                    <reward nature="Quirky" value="2"/>
                </answer>
            </question>
        </questiongroup>
        <questiongroup id="1">
            <question id="0">
                <answer id="0">
                    <reward nature="Docile" value="2"/>
                    <reward nature="Naive" value="1"/>
                </answer>
                <answer id="1">
                    <reward nature="Timid" value="2"/>
                    <reward nature="Calm" value="1"/>
                </answer>
            </question>
            <question id="1">
                <answer id="0">
                    <reward nature="Docile" value="2"/>
                    <reward nature="Hasty" value="1"/>
                </answer>
                <answer id="1">
                    <reward nature="Naive" value="2"/>
                    <reward nature="Relaxed" value="1"/>
                </answer>
            </question>
            <question id="2">
                <answer id="0">
                    <reward nature="Docile" value="2"/>
                </answer>
                <answer id="1">
                    <reward nature="Naive" value="2"/>
                    <reward nature="Lonely" value="1"/>
                </answer>
                <answer id="2">
                    <reward nature="Sassy" value="2"/>
                </answer>
            </question>
            <question id="3">
                <answer id="0">
                    <reward nature="Docile" value="2"/>
                </answer>
                <answer id="1">
                    <reward nature="Naive" value="2"/>
                </answer>
                <answer id="2">
                    <reward nature="Impish" value="2"/>
                </answer>
            </question>
        </questiongroup>
        <questiongroup id="2">
            <question id="0">
                <answer id="0">
                    <reward nature="Brave" value="3"/>
                    <reward nature="Impish" value="1"/>
                </answer>
                <answer id="1">
                    <reward nature="Docile" value="2"/>
                    <reward nature="Timid" value="1"/>
                </answer>
            </question>
            <question id="1">
                <answer id="0"/>
                <answer id="1">
                    <reward nature="Timid" value="2"/>
                </answer>
                <answer id="2">
                    <reward nature="Relaxed" value="2"/>
                </answer>
            </question>
            <question id="2">
                <answer id="0">
                    <reward nature="Brave" value="2"/>
                    <reward nature="Hardy" value="1"/>
                </answer>
                <answer id="1">
                    <reward nature="Naive" value="2"/>
                </answer>
            </question>
            <question id="3">
                <answer id="0">
                    <reward nature="Brave" value="3"/>
                </answer>
                <answer id="1">
                    <reward nature="Brave" value="2"/>
                    <reward nature="Hardy" value="2"/>
                </answer>
                <answer id="2">
                    <reward nature="Docile" value="1"/>
                    <reward nature="Timid" value="1"/>
                    <reward nature="Relaxed" value="1"/>
                </answer>
                <answer id="3">
                    <reward nature="Timid" value="2"/>
                </answer>
            </question>
        </questiongroup>
        <questiongroup id="3">
            <question id="0">
                <answer id="0">
                    <reward nature="Jolly" value="2"/>
                    <reward nature="Naive" value="1"/>
                </answer>
                <answer id="1">
                    <reward nature="Sassy" value="1"/>
                    <reward nature="Quirky" value="1"/>
                </answer>
            </question>
            <question id="1">
                <answer id="0">
                    <reward nature="Jolly" value="1"/>
                    <reward nature="Lonely" value="1"/>
                </answer>
                <answer id="1">
                    <reward nature="Timid" value="1"/>
                </answer>
            </question>
            <question id="2">
                <answer id="0">
                    <reward nature="Jolly" value="2"/>
                </answer>
                <answer id="1">
                    <reward nature="Calm" value="2"/>
                </answer>
                <answer id="1">
                    <reward nature="Quirky" value="2"/>
                </answer>
            </question>
            <question id="3">
                <answer id="0">
                    <reward nature="Jolly" value="3"/>
                </answer>
                <answer id="1">
                    <reward nature="Hardy" value="2"/>
                </answer>
                <answer id="2">
                    <reward nature="Timid" value="2"/>
                </answer>
            </question>
        </questiongroup>
        <questiongroup id="4">
            <question id="0">
                <answer id="0">
                    <reward nature="Impish" value="2"/>
                    <reward nature="Lonely" value="1"/>
                </answer>
                <answer id="1">
                    <reward nature="Calm" value="2"/>
                </answer>
            </question>
            <question id="1">
                <answer id="0">
                    <reward nature="Impish" value="2"/>
                </answer>
                <answer id="1">
                    <reward nature="Docile" value="1"/>
                    <reward nature="Relaxed" value="1"/>
                </answer>
            </question>
            <question id="2">
                <answer id="0">
                    <reward nature="Impish" value="2"/>
                    <reward nature="Hardy" value="1"/>
                </answer>
                <answer id="1">
                    <reward nature="Quirky" value="2"/>
                    <reward nature="Sassy" value="1"/>
                </answer>
            </question>
            <question id="3">
                <answer id="0">
                    <reward nature="Brave" value="3"/>
                </answer>
                <answer id="1">
                    <reward nature="Timid" value="2"/>
                </answer>
                <answer id="2">
                    <reward nature="Impish" value="2"/>
                </answer>
            </question>
        </questiongroup>
        <questiongroup id="5">
            <question id="0">
                <answer id="0">
                    <reward nature="Naive" value="3"/>
                    <reward nature="Impish" value="1"/>
                </answer>
                <answer id="1">
                    <reward nature="Jolly" value="2"/>
                </answer>
                <answer id="2">
                    <reward nature="Sassy" value="2"/>
                </answer>
            </question>
            <question id="1">
                <answer id="0">
                    <reward nature="Naive" value="2"/>
                    <reward nature="Docile" value="1"/>
                </answer>
                <answer id="1">
                    <reward nature="Quirky" value="2"/>
                </answer>
            </question>
            <question id="2">
                <answer id="0">
                    <reward nature="Naive" value="2"/>
                    <reward nature="Jolly" value="1"/>
                </answer>
                <answer id="1">
                    <reward nature="Calm" value="2"/>
                </answer>
            </question>
            <question id="3">
                <answer id="0">
                    <reward nature="Naive" value="2"/>
                </answer>
                <answer id="1">
                    <reward nature="Hasty" value="2"/>
                </answer>
            </question>
        </questiongroup>
        <questiongroup id="6">
            <question id="0">
                <answer id="0">
                    <reward nature="Timid" value="2"/>
                </answer>
                <answer id="1">
