=== Darkxell/PMDMMO/PMDMMO-common/resources/data/xsd/staticlayout.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="pmdmmo" targetNamespace="pmdmmo"
	elementFormDefault="qualified">
	<xs:include schemaLocation="base.xsd"/>

	<xs:element name="floor">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="cutscenein" type="xs:string" minOccurs="0"/>
				<xs:element name="cutscenestorypos" type="xs:integer" minOccurs="0"/>
				<xs:element ref="rooms"/>
				<xs:element name="tiles">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="row" maxOccurs="unbounded" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element ref="items"/>
				<xs:element ref="pokemons"/>
				<xs:element name="spawn">
					<xs:complexType>
						<xs:attribute name="x" type="posInt"/>
						<xs:attribute name="y" type="posInt"/>
						<xs:attribute name="facing" type="direction" use="optional"/>
					</xs:complexType>
				</xs:element>
				<xs:element ref="traps"/>
				<xs:element name="cutsceneout" type="xs:string" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="rooms">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="room" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="complex" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="room" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="room">
		<xs:complexType>
			<xs:attribute name="x" type="posInt"/>
			<xs:attribute name="y" type="posInt"/>
			<xs:attribute name="width" type="xs:positiveInteger"/>
			<xs:attribute name="height" type="xs:positiveInteger"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="items">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="item" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="id" type="posInt"/>
						<xs:attribute name="x" type="posInt"/>
						<xs:attribute name="y" type="posInt"/>
						<xs:attribute name="quantity" type="xs:positiveInteger" use="optional"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="pokemons">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="pokemon" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ai" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:token">
										<xs:enumeration value="skipper"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="boss" minOccurs="0"/>
						</xs:sequence>
						<xs:attribute name="id" type="posInt"/>
						<xs:attribute name="x" type="posInt"/>
						<xs:attribute name="y" type="posInt"/>
						<xs:attribute name="level" type="xs:positiveInteger"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="traps">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="trap" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="id" type="posInt"/>
						<xs:attribute name="x" type="posInt"/>
						<xs:attribute name="y" type="posInt"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Darkxell/PMDMMO/PMDMMO-common/resources/data/floors/3-9.xml
<?xml version="1.0" encoding="UTF-8"?>
<floor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="pmdmmo"
    xsi:schemaLocation="pmdmmo ../xsd/staticlayout.xsd">
    <rooms/>
    <tiles>
        <row>MMMMMMMMMMMMMMMMMMM</row>
        <row>MMMMMMMMMMMMMMMMMMM</row>
        <row>MMMMMMMMMMMMMMMMMMM</row>
        <row>MMMMMMMMMMMMMMMMMMM</row>
        <row>MMMMMMMMMMMMMMMMMMM</row>
        <row>MMMMMMMMMMMMMMMMMMM</row>
        <row>MMMMMMM     MMMMMMM</row>
        <row>MMMMM         MMMMM</row>
        <row>MMMMM         MMMMM</row>
        <row>MMMMM         MMMMM</row>
        <row>MMMMMMM     MMMMMMM</row>
        <row>MMMMMMMMMMMMMMMMMMM</row>
        <row>MMMMMMMMMMMMMMMMMMM</row>
        <row>MMMMMMMMMMMMMMMMMMM</row>
    </tiles>
    <items/>
    <pokemons>
        <pokemon id="227" x="9" y="6" level="10"/>
    </pokemons>
    <spawn x="9" y="8"/>
    <traps/>
</floor>
